version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: movein-postgres
    environment:
      POSTGRES_DB: movein_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: movein-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Backend API
  api:
    build: .
    container_name: movein-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/movein_db
      - JWT_ACCESS_SECRET=movein-super-secret-access-key-for-development-only
      - JWT_REFRESH_SECRET=movein-super-secret-refresh-key-for-development-only
      - JWT_ACCESS_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
      - PORT=3000
      - BCRYPT_ROUNDS=12
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - LOGIN_RATE_LIMIT_WINDOW_MS=900000
      - LOGIN_RATE_LIMIT_MAX_ATTEMPTS=5
      - CORS_ORIGIN=*
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=info
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

