platform :ios, '11.0'

target 'iosApp' do
  use_frameworks!
  
  # Firebase dependencies
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn'
  
  target 'iosAppTests' do
    inherit! :search_paths
  end
end
